### ISSUE TITLE
Not working for ads

### ISSUE THREAD

**Issue by mrx23dot** [EECSB/Google-Search-Customizer#20] opened 2022-12-15 23:11 UTC
I still see sponsored result:
https://www.google.com/search?client=opera&q=gerbv&sourceid=opera&ie=UTF-8&oe=UTF-8

![2022-12-16_001021](https://user-images.githubusercontent.com/4163396/207986182-f6808f66-d434-4cef-a5ea-55f794b7f4e3.jpg)

**Comment by EECSB** [comment] 2023-01-09 23:58
Hi.

Thanks for the bug report. It seems like google is making some changes to the ads section: [https://www.theverge.com/2022/10/14/23404396/google-mobile-search-results-ads-sponsored-site-names-favicons](https://www.theverge.com/2022/10/14/23404396/google-mobile-search-results-ads-sponsored-site-names-favicons)

I just have to make a few little changes to adjust for that in the extension. The problem is I am not able to see those changes yet. I assume Google is rolling out those changes gradually. 

I will leave this issue open for now and I will come back to it later when I can see the changes.

**Comment by mrx23dot** [comment] 2023-01-10 09:25
Could be some generic rule, search for bold "Sponsored" in text

**Comment by EECSB** [comment] 2023-01-10 16:39
This is how the ads appear to me:
![Screenshot_6](https://user-images.githubusercontent.com/50377992/211609326-e0c80f16-9c13-4a90-8746-1da9f199acd3.png)

**Comment by mrx23dot** [comment] 2023-01-10 16:44
weird, looks like this for me: (ignore the black)
![wwas](https://user-images.githubusercontent.com/4163396/211611352-29dbe4ce-e98e-451d-a2c1-26243631a074.png)

**Comment by Elnora** [comment] 2023-03-06 14:18
It's not working for me either - It's weird because it seems to work for just a split second and then it looks like it's loading again and then it's not working anymore.

![image](https://user-images.githubusercontent.com/10444300/223135421-8de1b43d-d74d-4e72-b5ca-60b66242e9eb.png)

**Comment by EECSB** [comment] 2024-02-04 20:22
This should be fixed now. If the problem is still there feel free to re-open the issue.

**Closed as completed by EECSB** 2024-02-04 20:22 UTC
